### ISSUE TITLE
Read configuration from Raw Config - Make the card consistent across tabs

### ISSUE THREAD

**Issue by eximo84** [joseluis9595/lovelace-navbar-card#10]
Really liking this card and want to improve the features.  Just wondering if there is a possibility to look at using a template config across dashboards/tabs via the raw configuration.

custom-button-card has a cool feature called templates, this allows you to store repeatable card configurations in the raw yaml and then call that code from each button card.

To ensure consistency it would be cool if something similar was implemented here, that way you dont need to deploy/copy paste the same card across all of your pages and tabs.  Then if something needs to change the edit is done in a single place rather than across each card instance.

![Image](https://github.com/user-attachments/assets/907fda58-3d8a-41aa-b2c9-16edfb5e2f25)

**Comment by joseluis9595** [comment]
This seems like a good idea! Will have to take a look and check how this could be implemented so that we don't lose functionality when using templates.

**Comment by joseluis9595** [comment]
@eximo84  Check out the [latest release](https://github.com/joseluis9595/lovelace-navbar-card/releases/tag/v0.1.0) 😄

**Comment by eximo84** [comment]
Getting the following card error

"routes" param is required for navbar card

Routes is defined in my template

Eg

```
navbar-templates:
  wall-tablet-nav:
    desktop:
      position: left
      min_width: 700
    routes:
      - icon: ios:house
        icon_selected: ios:house-fill
        url: /lovelace/main
        label: Home
```
