### ISSUE TITLE
[BUG] Icon selected does not work with anchor card

### ISSUE THREAD

**Issue by bladecell** [joseluis9595/lovelace-navbar-card#27]
**Describe the bug**
The `icon_selected` does not work when using parameters in the url when using the [anchor card](https://github.com/ShadowAya/anchor-card).
When comparing the urls parameters could be stripped, because the url will be without the `anchor` parameter

**navbar-card yaml configuration**
```yaml
routes:
  - icon: m3r:home
    icon_selected: mdi:home-assistant
    url: /bum-dash/home_view?anchor=home
    label: Overview
```

**Comment by joseluis9595** [comment]
I think the current implementation should be the expected behaviour. One possible way to bypass this could be to introduce a templatable `selected` field for each route, where the user could define custom conditions to display a route as selected.

For example: 

```yaml
type: custom:lovelace-navbar-card
...
routes:
  ...
  - icon: m3r:home
    icon_selected: mdi:home-assistant
    url: /bum-dash/home_view?anchor=home
    label: Overview
    selected: > 
      const fullPath = window.location.pathname + window.location.search;
      return fullPath.startsWith('/bum-dash/home_view?anchor=home')
```

What do you think?
