### ISSUE TITLE
[Feature] Change Spacing

### ISSUE THREAD

**Issue by prestr** [joseluis9595/lovelace-navbar-card#66]
**Is your feature request related to a problem? Please describe.**
On iOS the furthest left and right buttons when highlighted get cut off the screen because the screen is rounded along the edges.

**Describe the solution you'd like**
I'd like a way to space the icons so I can move them more inward on the navbar so they are closer together and don't get cut off.

**Comment by prestr** [comment]
As a workaround I've created a blank icon on the left and right now.

**Comment by joseluis9595** [comment]
You can use the `styles` props for that. Not really sure if it's something I can detect via code, to automatically add padding for said devices, but in the meantime you can try this, adapting the `20px` to your desired padding:

```yaml
type: custom:navbar-card
...
styles: |
  .navbar.mobile {
    padding-left: 20px;
    padding-right: 20px;
  }
```
