### ISSUE TITLE
[BUG] Button background stays highlighted

### ISSUE THREAD

**Issue by prestr** [joseluis9595/lovelace-navbar-card#68]
**Describe the bug**
After tapping a navigation button and then returning to that dashboard, the navigation button's background is highlighted.

**To Reproduce**
1. Create a navigation bar with 2 (or more) buttons that link to two different dashboards, and put it on both dashboards
2. Tap the second  navigation button to switch to the second dashboard
3. Tap the first button to return to the first dashboard

**Expected behavior**
Button background wont be highlighted. 

**Screenshots**
I started on the first dashboard (with the HA icon), tapped the battery icon, then tapped the HA button. The battery icon has a highlighted background.
 

![Image](https://github.com/user-attachments/assets/e0dd3afd-b51d-4063-8a92-9cc95b2fdc82)

**Information (please complete the following information):**
- iOS 18.5
- HA version 2025.5.3

**navbar-card yaml configuration**
```yaml
type: custom:navbar-card
desktop:
  hidden: true
routes:
  - url: /lovelace/home
    icon: mdi:home-assistant
    label: Home
  - url: /lovelace/batteries
    icon: mdi:battery-70
    label: Batteries
  - url: /lovelace/cameras
    icon: mdi:video
    label: Automations
  - icon: mdi:dots-horizontal
    label: More
    tap_action:
      action: open-popup
    popup:
      - icon: mdi:math-log
        url: /config/logs
      - icon: mdi:cog
        url: /config/dashboard
      - icon: mdi:power
        tap_action:
          action: call-service
          service: homeassistant.restart
          service_data: {}
          confirmation:
            text: Are you sure you want to restart Home Assistant?
styles: |
  .navbar {
    background-color: transparent;
  }
  .button.active {
    background: transparent;
    --icon-primary-color: slategrey;
  }
  .navbar.mobile { 
    padding-left: 65px; 
    padding-right: 65px;
    bottom: 15px;
    --navbar-box-shadow: transparent;
  }
```
