### ISSUE TITLE
[BUG] Badge Problem

### ISSUE THREAD

**Issue by clipse2004** [joseluis9595/lovelace-navbar-card#72]
**Describe the bug**
 I have an issue with the badge.
I created a row with rooms and assigned the following to the badge:

badge:
  show: >
    [[[ states['binary_sensor.aktivitat_esszimmer'].state ===
      'on' ]]]
  color: var(--primary-color)

I would expect a red circle to appear above the badge when the activity is set to 'on'. However, that simply doesn't work. But if I insert your example instead, then it works.

**Expected behavior**
When there is activity in a specific room, a red badge should appear.

**Screenshots**

**Information (please complete the following information):**
 - OS: iOS
 - Browser: Safari
 - Navbar-card version v0.11.0
- HA version 2025.6.1

**navbar-card yaml configuration**
```yaml
navbar-templates:
  navbar_template:
    desktop:
      position: right
      show_labels: true
      haptic: true
    mobile:
      show_labels: true
      haptic: true
    routes:
      - url: /lovelace/home
        icon: mdi:home
        icon_selected: mdi:home-variant
        label: Home
      - icon: fas:house-user
        label: Räume
        tap_action:
          action: open-popup
        popup:
          - icon: phu:rooms-outdoor
            url: /lovelace/garten
            label: Garten
            badge:
              show: >
                [[[ states['binary_sensor.aktivitat_terrasse'].state === 'on' ]]]
              color: var(--primary-color)
```
