### ISSUE TITLE
[BUG] theme padding not applied

### ISSUE THREAD

**Issue by victorigualada** [joseluis9595/lovelace-navbar-card#73]
**Describe the bug**
After updating to `v0.11.0`, the padding addition through a custom theme and `card-mod` doesn't work anymore.

**To Reproduce**
1. Add the configuration to the custom theme as explained here: https://github.com/joseluis9595/lovelace-navbar-card?tab=readme-ov-file#padding
2. Observe that the padding is not applied

**Expected behavior**
The padding (and potentially other styles but I haven't verified) should be applied to the `hui-sections-view` element.

**Information (please complete the following information):**
 - Navbar-card version: `v0.11.0`
- HA version: `2025.6.2`

**navbar-card yaml configuration**
Not relevant as it's a very basic menu without any modification besides the padding applied to the theme

**Comment by joseluis9595** [comment]
Hi! The padding configuration is a native HA theme configuration, so new releases of navbar-card have no impact in its behaviour. 
Maybe you updated HA version? Or even changed your dashboard type? I'll bump my testing HA instance to `2025.6.2` and check whether the code in the README.md is no longer working, just in case

**Comment by joseluis9595** [comment]
Take a look at [the latest version of the README.md](https://github.com/joseluis9595/lovelace-navbar-card?tab=readme-ov-file#padding), now it should be working for all dashboard types. 

Closing this for now, if the issue persists, let me know and I'll reopen it 🙂

**Comment by victorigualada** [comment]
This is not working either. I'm using sections so the previous config should have work also. 
After looking at the commits I can't see anything that would have broken the behavior though.
I tried with other themes too but got the same result, there is not padding added in any screen size.

**Comment by joseluis9595** [comment]
The snippet for the dashboard padding, is completely independent from navbar-card. It's useful for preventing overlap, but it does not rely at all in navbar-card implementation, as it is native to HA.
With that said, the snippet provided in the README can have typos, or even not be working for some HA versions.

Can you try adding something more visual to the theme, to check if it is loading at all? Like changing the background to red for example. This is the theme I'm using in my test instance of HA, working with a sections dashboard, and correctly applying both the padding, and the hardcoded red background:

```yaml
custom_theme:
  app-header-background-color: transparent
  app-header-text-color: var(--primary-text-color)

  card-mod-theme: custom_theme
  card-mod-root-yaml: |
    .: |
      /* Add padding to the left (or other sides, depending on your navbar position) for desktop screens */
      @media (min-width: 768px) {
        :not(.edit-mode) > #view {
          padding-left: 100px !important;
          background: red !important;
        }
      }

      /* Add bottom padding for mobile screens to prevent cards from overlapping with the navbar */
      @media (max-width: 767px) {
        :not(.edit-mode) > hui-view:after {
          content: "";
          display: block;
          height: 80px;
          width: 100%;
          background-color: transparent; 
        }
      }

      .toolbar > sl-tab-group {
        pointer-events: none;
        opacity: 0;
      }
      

```
